controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true
    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Neck_Yaw
      - Neck_Pitch
      - TorsoShoulder_Left_Pitch
      - TorsoShoulder_Left_Roll
      - ShoulderElbow_Left
      - TorsoShoulder_Right_Pitch
      - TorsoShoulder_Right_Roll
      - ShoulderElbow_Right
      - TorsoThigh_Left_Pitch
      - TorsoThigh_Left_Yaw
      - ThighCalf_Left
      - CalfFoot_Left
      - TorsoThigh_Right_Pitch
      - TorsoThigh_Right_Yaw
      - ThighCalf_Right
      - CalfFoot_Right

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gazebo_ros2_control:
  ros__parameters:
    pid_gains:
      position:
        Neck_Yaw: {kp: 50.0, ki: 0.5, kd: 5.0, max_integral_error: 10000.0}
        Neck_Pitch: {kp: 50.0, ki: 0.5, kd: 5.0, max_integral_error: 10000.0}
        TorsoShoulder_Left_Pitch: {kp: 100.0, ki: 1.0, kd: 10.0, max_integral_error: 10000.0}
        TorsoShoulder_Left_Roll: {kp: 100.0, ki: 1.0, kd: 10.0, max_integral_error: 10000.0}
        ShoulderElbow_Left: {kp: 30.0, ki: 0, kd: 2.0, max_integral_error: 10000.0}
        TorsoShoulder_Right_Pitch: {kp: 100.0, ki: 1.0, kd: 10.0, max_integral_error: 10000.0}
        TorsoShoulder_Right_Roll: {kp: 100.0, ki: 1.0, kd: 10.0, max_integral_error: 10000.0}
        ShoulderElbow_Right: {kp: 30.0, ki: 0, kd: 2.0, max_integral_error: 10000.0}
        TorsoThigh_Left_Pitch: {kp: 250.0, ki: 2.5, kd: 25.0, max_integral_error: 10000.0}
        TorsoThigh_Left_Yaw: {kp: 150.0, ki: 1.5, kd: 15.0, max_integral_error: 10000.0}
        ThighCalf_Left: {kp: 200.0, ki: 2.0, kd: 20.0, max_integral_error: 10000.0}
        CalfFoot_Left: {kp: 150.0, ki: 1.5, kd: 15.0, max_integral_error: 10000.0}
        TorsoThigh_Right_Pitch: {kp: 250.0, ki: 2.5, kd: 25.0, max_integral_error: 10000.0}
        TorsoThigh_Right_Yaw: {kp: 150.0, ki: 1.5, kd: 15.0, max_integral_error: 10000.0}
        ThighCalf_Right: {kp: 200.0, ki: 2.0, kd: 20.0, max_integral_error: 10000.0}
        CalfFoot_Right: {kp: 150.0, ki: 1.5, kd: 15.0, max_integral_error: 10000.0}

