name: Input Test
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ROS2 and dependencies
        run: |
          sudo bash ros_requirements.sh    

      - name: Build Workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

          source install/setup.bash
      
      - name: Play Sensor_Bag and Run Tests
        run: |
          colcon build --symlink-install
          source /opt/ros/humble/setup.bash
          source install/setup.bash

          ros2 launch humanoid_robot test.launch.py &
          sleep 10  # Give the nodes time to launch
          python3 -m pytest scripts/tests/test_inputs.py
